### 회원 가입
POST http://localhost:8080/members
Content-Type: application/json

{
  "email": "abc123@gmail.com",
  "password": "pa**@@rd",
  "age": 20
}

### 로그인
POST http://localhost:8080/login/token
Content-Type: application/json

{
  "email": "abc123@gmail.com",
  "password": "pa**@@rd"
}

### 경로 조회
GET http://localhost:8080/paths?source=3&target=7

### 지하철 역 조회
GET http://localhost:8080/stations

### 지하철 노선 조회
GET http://localhost:8080/lines/1