version: "3"
services:
  subway:
    image: pageprologue/subway-monitoring:0.1
    container_name: subway-monitoring
    ports:
      - "80:8080"
    environment:
      - SPRING_PROFILE=prod
    volumes:
      - ../logs:/logs
