version: "3"
services:
  mysql:
    image: brainbackdoor/data-subway:0.0.1
    restart: always
    container_name: subway_mysql-k6
    ports:
      - "13306:3306"
    volumes:
      - ../mysql/data:/var/lib/mysql
      - ../mysql/conf.d/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_ROOT_PASSWORD: masterpw
      MYSQL_DATABASE: subway
  subway:
    image: pageprologue/subway-monitoring:0.2
    container_name: subway-k6
    ports:
      - "8888:8080"
    environment:
      - SPRING_PROFILE=prod
    volumes:
      - ../logs/k6:/logs
    depends_on:
      - mysql
